name: "yuki"
dev:
  host: "10.24.21.110"
  port: 22
  username: "root"
  password: "Datayes#@!"
  localPath: "/dist"
  remotePath: "/usr/local/src/"
  backupPath: "/usr/local/src/backup"
stg:
  host: "10.24.90.48"
  port: 22
  username: "root"
  password: "Datayes#@!"
  localPath: "/dist"
  remotePath: "/usr/local/src/"
  backupPath: "/usr/local/src/backup"
qa:
  host: "10.24.21.148"
  port: 22
  username: "root"
  password: "Datayes#@!"
  localPath: "/dist"
  remotePath: "/usr/local/src/"
  backupPath: "/usr/local/src/backup"
prd:
  host: "10.21.141.50"
  port: 22
  username: "root"
  password: "Datayes#@!"
  localPath: "/dist"
  remotePath: "/usr/local/src/"
  backupPath: "/usr/local/src/backup"